export enum Event {
  burn = 'Uniques.Burned',
  changeIssuer = 'Uniques.OwnerChanged',
  changeOwnershipAcceptance = 'Uniques.OwnershipAcceptanceChanged',
  changeTeam = 'Uniques.TeamChanged',
  clearAttribute = 'Uniques.AttributeCleared',
  clearClassMetadata = 'Uniques.ClassMetadataCleared',
  clearCollectionMetadata = 'Uniques.CollectionMetadataCleared',
  clearMetadata = 'Uniques.MetadataCleared',
  clearPrice = 'Uniques.ItemPriceRemoved',
  createCollection = 'Uniques.Created',
  createItem = 'Uniques.Issued',
  destroyCollection = 'Uniques.Destroyed',
  forceCreateClass = 'Uniques.ForceCreated',
  freeze = 'Uniques.Frozen',
  freezeClass = 'Uniques.ClassFrozen',
  freezeCollection = 'Uniques.CollectionFrozen',
  setAttribute = 'Uniques.AttributeSet',
  setClassMetadata = 'Uniques.ClassMetadataSet',
  setCollectionMaxSupply = 'Uniques.CollectionMaxSupplySet',
  setCollectionMetadata = 'Uniques.CollectionMetadataSet',
  setMetadata = 'Uniques.MetadataSet',
  setPrice = 'Uniques.ItemPriceSet',
  sold = 'Uniques.ItemBought',
  thaw = 'Uniques.Thawed',
  thawClass = 'Uniques.ClassThawed',
  thawCollection = 'Uniques.CollectionThawed',
  transfer = 'Uniques.Transferred',
}

